### PR TITLE
adds pul-icons to svg-icon component

### LINKED ISSUE #28: Namespace Icons

### LINKED ISSUE #48: Clean up icons in assets folder
Add only PUL-icons and logos in icons folder

### PR DESCRIPTION
**Pull request by sdellis**
Fixes #48 by cleaning up icons folder. Also fixes #28 by namespacing icons with `pul-icon` prefix.

### CODE REVIEW

**Comment by axamei** [comment]
@sdellis Are the University logos showing up as orange for you?
screen shot 2018-06-07 at 4 23 05 pm

**Comment by sdellis** [comment]
@axamei Yes, good catch! Looking into it...

**Comment by sdellis** [comment]
TLDR; WIP - don't merge yet

I partially figured this out, but ran out of time and will need to finish up tomorrow. SVG icons have a fill attribute... with logos, we need to use the colors specified. In the case of the white logos, some fill is getting set in the docs, so I need to to make sure it doesn't apply to the logo svgs.

**Comment by axamei** [comment]
@sdellis I think this issue might be that these logos are multi-colored and are using the same class names for the different paths, e.g., `.a{fill:none;}.b{fill:#fbfbfb;}.c{fill:#fff;}` and `.a{fill:#ed6d0b;}.b{fill:#000;}.c{fill:#fff;isolation:isolate;}`

**Comment by sdellis** [comment]
@axamei I tried changing the class names in the svg files, but it doesn't seem to make any difference. What's strange to me is that the university-logo looks fine, while the other ones are getting the incorrect fills...

**Comment by axamei** [comment]
@sdellis The styles (fill) of the last logo is cascading into the other ones. I posted some svgs on Slack. They are working on my local. Do you want me to add a commit to this PR?

**Comment by axamei** [comment]
@sdellis I'm wondering if we should remove the logos from this PR for now and consider adding them as components with options/variations that are determined based on props.

Perhaps something along the lines of `UniversityLogo.vue` and `LibraryLogo.vue`. University Logo would have "one-line" or "two-line" and "black", "white", "multi-color" options.

**Comment by axamei** [comment]
👍

**Pull request merged**
