### PR TITLE
Adds DatePicker Component

### PR DESCRIPTION
**Pull request by sdellis**
Still need to debug popover defaults and input-text integration

### CODE REVIEW

**Comment by sdellis** [comment]
Having problems with the testing of this due to the css import. Possible solution: https://github.com/vuejs/vue-test-utils/issues/1011

**Comment by sdellis** [comment]
Testing issues have been resolved via additional jest configuration to allow for CSS imports. @axamei , should be ready to merge if you are 👍 .

**Comment by axamei** [comment]
Looks good. Thanks @sdellis

**Comment by axamei** [comment]
Advances #168

**Pull request merged**
