### PR TITLE
Code cleanup and makes updates to static build instructions

### PR DESCRIPTION
**Pull request by sdellis**

### CODE REVIEW

**Comment by axamei** [comment]
@sdellis Do we want to bump up vue-styleguidist to v2.0.1 in our package.json to resolve the code block issue?

**Comment by sdellis** [comment]
@axamei That's probably a good move. Of course, I moved all of the problematic documentation out to the project wiki, but it may be best to add it back in. I'll do it now and see if it works.

**Comment by sdellis** [comment]
@axamei Thanks for the heads-up. That worked out really well. Once this is published, I'll remove the duplicate documentation in the wiki and we can keep it all in the docs once again. :tada:

This is now ready for merge and publish.

**Comment by sdellis** [comment]
Oops... spoke too soon... one more tweak

**Comment by sdellis** [comment]
Ok, finally ready for merge and publish, @axamei !

**Comment by axamei** [comment]
👍

**Pull request merged**
